/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreatFlowsIndexRouteImport } from './routes/threat-flows/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as ThreatFlowsFlowIdRouteImport } from './routes/threat-flows/$flowId'
import { Route as ThreatFlowTemplatesRouteImport } from './routes/threat-flow/templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatFlowsIndexRoute = ThreatFlowsIndexRouteImport.update({
  id: '/threat-flows/',
  path: '/threat-flows/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatFlowsFlowIdRoute = ThreatFlowsFlowIdRouteImport.update({
  id: '/threat-flows/$flowId',
  path: '/threat-flows/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatFlowTemplatesRoute = ThreatFlowTemplatesRouteImport.update({
  id: '/threat-flow/templates',
  path: '/threat-flow/templates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/threat-flow/templates': typeof ThreatFlowTemplatesRoute
  '/threat-flows/$flowId': typeof ThreatFlowsFlowIdRoute
  '/templates': typeof TemplatesIndexRoute
  '/threat-flows': typeof ThreatFlowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/threat-flow/templates': typeof ThreatFlowTemplatesRoute
  '/threat-flows/$flowId': typeof ThreatFlowsFlowIdRoute
  '/templates': typeof TemplatesIndexRoute
  '/threat-flows': typeof ThreatFlowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/threat-flow/templates': typeof ThreatFlowTemplatesRoute
  '/threat-flows/$flowId': typeof ThreatFlowsFlowIdRoute
  '/templates/': typeof TemplatesIndexRoute
  '/threat-flows/': typeof ThreatFlowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/threat-flow/templates'
    | '/threat-flows/$flowId'
    | '/templates'
    | '/threat-flows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/threat-flow/templates'
    | '/threat-flows/$flowId'
    | '/templates'
    | '/threat-flows'
  id:
    | '__root__'
    | '/'
    | '/threat-flow/templates'
    | '/threat-flows/$flowId'
    | '/templates/'
    | '/threat-flows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThreatFlowTemplatesRoute: typeof ThreatFlowTemplatesRoute
  ThreatFlowsFlowIdRoute: typeof ThreatFlowsFlowIdRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ThreatFlowsIndexRoute: typeof ThreatFlowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-flows/': {
      id: '/threat-flows/'
      path: '/threat-flows'
      fullPath: '/threat-flows'
      preLoaderRoute: typeof ThreatFlowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-flows/$flowId': {
      id: '/threat-flows/$flowId'
      path: '/threat-flows/$flowId'
      fullPath: '/threat-flows/$flowId'
      preLoaderRoute: typeof ThreatFlowsFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-flow/templates': {
      id: '/threat-flow/templates'
      path: '/threat-flow/templates'
      fullPath: '/threat-flow/templates'
      preLoaderRoute: typeof ThreatFlowTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThreatFlowTemplatesRoute: ThreatFlowTemplatesRoute,
  ThreatFlowsFlowIdRoute: ThreatFlowsFlowIdRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ThreatFlowsIndexRoute: ThreatFlowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
